apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" $ }}-proxmox-cloud-provider-config
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    features:
      provider: capmox
    clusters:
      - url: {{ .Values.global.providerSpecific.proxmox.url | b64enc | quote }}
        insecure: {{ .Values.global.providerSpecific.proxmox.insecure | b64enc | quote }}
        token_id: {{ .Values.global.providerSpecific.proxmox.token | b64enc | quote }}
        token_secret: {{ .Values.global.providerSpecific.proxmox.secret | b64enc | quote }}
        region: {{ .Values.global.providerSpecific.proxmox.clusterName | b64enc | quote }}
