apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" $ }}-proxmox-cloud-provider-config
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: {{ include "cloudProviderProxmoxSecret" $ | b64enc -}}
