apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credentialSecretName" $ }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  secret: {{ .Values.global.providerSpecific.proxmox.secret | b64enc | quote }}
  token: {{ .Values.global.providerSpecific.proxmox.token | b64enc | quote }}
  url: {{ .Values.global.providerSpecific.proxmox.url | b64enc | quote }}