apiVersion: {{ include "infrastructureApiVersion" . }}
kind: ProxmoxCluster
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    {{- include "preventDeletionLabel" $ | nindent 4 }}
spec:
  {{- if .Values.global.providerSpecific.proxmox.allowedNodes }}
  allowedNodes:
  {{- range $node := .Values.global.providerSpecific.proxmox.allowedNodes }}
  - {{ $node }}
  {{- end }}
  {{- end }}
  controlPlaneEndpoint:
    # The ProxmoxCluster cannot be created without a valid host address (it gets rejected by the CAPMOX
    # admission webhook), but if we want to dynamically allocate the host address using IPAM then we cannot
    # know it ahead of time and so we have a chicken and egg problem. To work around this, we default to a
    # dummy value here (which only gets used if an IP hasn't been set in the chart's values, and then we
    # patch the ProxmoxCluster with the correct value via the IPAM update-values Job.
    host: '{{ ((.Values.global.connectivity.network).controlPlaneEndpoint).host | default "10.0.0.1" }}'
    port: {{ ((.Values.global.connectivity.network).controlPlaneEndpoint).port | default 6443 }}
  dnsServers:
  {{- range $server := .Values.global.providerSpecific.proxmox.dnsServers }}
  - {{ $server }}
  {{- end }}
  ipv4Config:
    addresses:
    {{- range $addresses := .Values.global.providerSpecific.proxmox.ipv4Config.addresses }}
    - {{ $addresses }}
    {{- end }}
    gateway: {{ .Values.global.providerSpecific.proxmox.ipv4Config.gateway }}
    prefix: {{ .Values.global.providerSpecific.proxmox.ipv4Config.prefix }}
  credentialsRef:
    name: {{ include "credentialSecretName" $ }}