#
# This HelmRelease creates the kube-vip cloud-controller-manager which is responsible for
# managing IP addresses for the Service loadbalancers.
#
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-proxmox-cloud-provider
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.global.metadata.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: proxmox-cloud-controller-manager
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: proxmox-cloud-controller-manager
      {{- $_ := set $ "appName" "proxmox-cloud-controller-manager" }}
      version: {{ include "cluster.app.version" $ }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-{{ include "cluster.app.catalog" $ }}
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-cilium
      namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  values:
    config:
      features:
        provider: capmox
        network:
          mode: auto
      clusters:
        - url: {{ include "cloudControllerManagerURL" $ }}
          insecure: {{ .Values.global.providerSpecific.proxmox.insecure  }}
          token_id: {{ .Values.global.providerSpecific.proxmox.cloudControllerManager.token | quote }}
          token_secret: {{ .Values.global.providerSpecific.proxmox.cloudControllerManager.secret | quote }}
          region: {{ .Values.global.providerSpecific.proxmox.clusterName | quote }}
