#
# This HelmRelease creates the kube-vip daemonset which advertises the consumed IPs from the
# range allocated to the Service loadbalancers.
#
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: {{ include "resource.default.name" $ }}-kube-vip
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  {{- $_ := set $ "appName" "kube-vip" }}
  url: oci://gsoci.azurecr.io/charts/giantswarm/kube-vip
  ref:
    tag: {{ include "cluster.app.version" $ }}
  interval: 24h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-kube-vip
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.global.metadata.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: kube-vip
  targetNamespace: kube-system
  storageNamespace: kube-system
  chartRef:
    kind: OCIRepository
    name: {{ include "resource.default.name" $ }}-kube-vip
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-cilium
      namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  values:
    env:
      vip_interface: "eth0"
